### Get All Products With Stat
GET http://localhost:5001/client/products

### Get All Customers
GET http://localhost:5001/client/customers

### Get All Transactions (With Pagination)
GET http://localhost:5001/client/transactions

### Get All Geography
GET http://localhost:5001/client/geography
